import { Brand, DeviceModel, ConditionQuestion, RefurbProduct, SellOrder, BuyOrder, Quote } from '@/types';

export const BRANDS: Brand[] = [
  { id: 'apple', name: 'Apple', slug: 'apple', category: 'phone', logo: '🍎', popular: true },
  { id: 'samsung', name: 'Samsung', slug: 'samsung', category: 'phone', logo: '📱', popular: true },
  { id: 'oneplus', name: 'OnePlus', slug: 'oneplus', category: 'phone', logo: '⚡', popular: true },
  { id: 'xiaomi', name: 'Xiaomi / Redmi', slug: 'xiaomi', category: 'phone', logo: '🟠', popular: true },
  { id: 'google', name: 'Google Pixel', slug: 'google', category: 'phone', logo: '🔍', popular: true },
  { id: 'vivo', name: 'Vivo', slug: 'vivo', category: 'phone', logo: '🔷', popular: true },
  { id: 'oppo', name: 'Oppo', slug: 'oppo', category: 'phone', logo: '🟢', popular: false },
  { id: 'realme', name: 'Realme', slug: 'realme', category: 'phone', logo: '🟡', popular: false },
];

export const MODELS: DeviceModel[] = [
  // Apple
  {
    id: 'iphone-15-pro',
    brandId: 'apple',
    name: 'iPhone 15 Pro',
    slug: 'iphone-15-pro',
    category: 'phone',
    imageUrl: 'https://images.unsplash.com/photo-1695048133142-1a20484d2569?auto=format&fit=crop&w=600&q=80',
    popular: true,
    releaseYear: 2023,
    variants: [
      { id: 'i15p-128', modelId: 'iphone-15-pro', ram: '8GB', storage: '128GB', basePrice: 72000 },
      { id: 'i15p-256', modelId: 'iphone-15-pro', ram: '8GB', storage: '256GB', basePrice: 81000 },
      { id: 'i15p-512', modelId: 'iphone-15-pro', ram: '8GB', storage: '512GB', basePrice: 95000 },
    ],
  },
  {
    id: 'iphone-14',
    brandId: 'apple',
    name: 'iPhone 14',
    slug: 'iphone-14',
    category: 'phone',
    imageUrl: 'https://images.unsplash.com/photo-1663499482523-1c0c1bae4ce1?auto=format&fit=crop&w=600&q=80',
    popular: true,
    releaseYear: 2022,
    variants: [
      { id: 'i14-128', modelId: 'iphone-14', ram: '6GB', storage: '128GB', basePrice: 42000 },
      { id: 'i14-256', modelId: 'iphone-14', ram: '6GB', storage: '256GB', basePrice: 48000 },
    ],
  },
  {
    id: 'iphone-13',
    brandId: 'apple',
    name: 'iPhone 13',
    slug: 'iphone-13',
    category: 'phone',
    imageUrl: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=600&q=80',
    popular: true,
    releaseYear: 2021,
    variants: [
      { id: 'i13-128', modelId: 'iphone-13', ram: '4GB', storage: '128GB', basePrice: 33000 },
      { id: 'i13-256', modelId: 'iphone-13', ram: '4GB', storage: '256GB', basePrice: 38000 },
    ],
  },
  {
    id: 'iphone-12',
    brandId: 'apple',
    name: 'iPhone 12',
    slug: 'iphone-12',
    category: 'phone',
    imageUrl: 'https://images.unsplash.com/photo-1605236453806-6ff36851218e?auto=format&fit=crop&w=600&q=80',
    popular: false,
    releaseYear: 2020,
    variants: [
      { id: 'i12-64', modelId: 'iphone-12', ram: '4GB', storage: '64GB', basePrice: 22000 },
      { id: 'i12-128', modelId: 'iphone-12', ram: '4GB', storage: '128GB', basePrice: 25000 },
    ],
  },
  // Samsung
  {
    id: 'galaxy-s24-ultra',
    brandId: 'samsung',
    name: 'Galaxy S24 Ultra',
    slug: 'galaxy-s24-ultra',
    category: 'phone',
    imageUrl: 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?auto=format&fit=crop&w=600&q=80',
    popular: true,
    releaseYear: 2024,
    variants: [
      { id: 's24u-256', modelId: 'galaxy-s24-ultra', ram: '12GB', storage: '256GB', basePrice: 78000 },
      { id: 's24u-512', modelId: 'galaxy-s24-ultra', ram: '12GB', storage: '512GB', basePrice: 88000 },
    ],
  },
  {
    id: 'galaxy-s23',
    brandId: 'samsung',
    name: 'Galaxy S23 5G',
    slug: 'galaxy-s23',
    category: 'phone',
    imageUrl: 'https://images.unsplash.com/photo-1580910051074-3eb694886505?auto=format&fit=crop&w=600&q=80',
    popular: true,
    releaseYear: 2023,
    variants: [
      { id: 's23-128', modelId: 'galaxy-s23', ram: '8GB', storage: '128GB', basePrice: 38000 },
      { id: 's23-256', modelId: 'galaxy-s23', ram: '8GB', storage: '256GB', basePrice: 43000 },
    ],
  },
  // OnePlus
  {
    id: 'oneplus-12',
    brandId: 'oneplus',
    name: 'OnePlus 12',
    slug: 'oneplus-12',
    category: 'phone',
    imageUrl: 'https://images.unsplash.com/photo-1565849904461-04a58ad377e0?auto=format&fit=crop&w=600&q=80',
    popular: true,
    releaseYear: 2024,
    variants: [
      { id: 'op12-256', modelId: 'oneplus-12', ram: '12GB', storage: '256GB', basePrice: 45000 },
      { id: 'op12-512', modelId: 'oneplus-12', ram: '16GB', storage: '512GB', basePrice: 52000 },
    ],
  },
  {
    id: 'oneplus-11r',
    brandId: 'oneplus',
    name: 'OnePlus 11R 5G',
    slug: 'oneplus-11r',
    category: 'phone',
    imageUrl: 'https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&w=600&q=80',
    popular: true,
    releaseYear: 2023,
    variants: [
      { id: 'op11r-128', modelId: 'oneplus-11r', ram: '8GB', storage: '128GB', basePrice: 24000 },
      { id: 'op11r-256', modelId: 'oneplus-11r', ram: '16GB', storage: '256GB', basePrice: 28000 },
    ],
  },
  // Google Pixel
  {
    id: 'pixel-8-pro',
    brandId: 'google',
    name: 'Google Pixel 8 Pro',
    slug: 'pixel-8-pro',
    category: 'phone',
    imageUrl: 'https://images.unsplash.com/photo-1592899677977-9c10ca588bbd?auto=format&fit=crop&w=600&q=80',
    popular: true,
    releaseYear: 2023,
    variants: [
      { id: 'p8p-128', modelId: 'pixel-8-pro', ram: '12GB', storage: '128GB', basePrice: 50000 },
      { id: 'p8p-256', modelId: 'pixel-8-pro', ram: '12GB', storage: '256GB', basePrice: 56000 },
    ],
  },
  // Xiaomi
  {
    id: 'redmi-note-13-pro',
    brandId: 'xiaomi',
    name: 'Redmi Note 13 Pro+ 5G',
    slug: 'redmi-note-13-pro',
    category: 'phone',
    imageUrl: 'https://images.unsplash.com/photo-1546868871-7041f2a55e12?auto=format&fit=crop&w=600&q=80',
    popular: true,
    releaseYear: 2024,
    variants: [
      { id: 'rn13p-256', modelId: 'redmi-note-13-pro', ram: '8GB', storage: '256GB', basePrice: 19000 },
      { id: 'rn13p-512', modelId: 'redmi-note-13-pro', ram: '12GB', storage: '512GB', basePrice: 22000 },
    ],
  }
];

export const CONDITION_QUESTIONS: ConditionQuestion[] = [
  {
    id: 'q_switch_on',
    category: 'phone',
    orderIndex: 1,
    title: 'Does your phone turn on and function?',
    description: 'Check whether the screen lights up, accepts touch and can boot into home screen.',
    type: 'single',
    options: [
      {
        id: 'power_yes',
        label: 'Yes, works perfectly',
        description: 'Phone turns on and boots normally without reboot loops',
        deductionType: 'percent',
        deductionValue: 0,
        icon: 'check-circle'
      },
      {
        id: 'power_reboot',
        label: 'Restarts intermittently',
        description: 'Phone turns on but randomly freezes or reboots',
        deductionType: 'percent',
        deductionValue: 25,
        icon: 'alert-triangle'
      },
      {
        id: 'power_no',
        label: 'Dead / Does not turn on',
        description: 'Phone does not boot up or display any sign of life',
        deductionType: 'percent',
        deductionValue: 65,
        icon: 'x-circle'
      }
    ]
  },
  {
    id: 'q_screen_condition',
    category: 'phone',
    orderIndex: 2,
    title: 'What is the condition of the screen display?',
    description: 'Inspect the glass surface and the underlying display panel closely under light.',
    type: 'single',
    options: [
      {
        id: 'screen_flawless',
        label: 'Flawless / Pristine',
        description: 'Zero scratches, no lines, no yellow spots or pixel bleed',
        deductionType: 'percent',
        deductionValue: 0,
        icon: 'sparkles'
      },
      {
        id: 'screen_minor_scratches',
        label: 'Minor Hairline Scratches',
        description: 'Light scratches visible only under direct lamp light',
        deductionType: 'flat',
        deductionValue: 1200,
        icon: 'eye'
      },
      {
        id: 'screen_cracked',
        label: 'Cracked Glass / Broken Screen',
        description: 'Visible cracks or chips on outer front glass',
        deductionType: 'flat',
        deductionValue: 4500,
        icon: 'slash'
      },
      {
        id: 'screen_display_defects',
        label: 'Lines / Dead Pixels / Spot',
        description: 'Green/pink vertical lines, dark liquid spots or touch failure',
        deductionType: 'flat',
        deductionValue: 7000,
        icon: 'x-octagon'
      }
    ]
  },
  {
    id: 'q_body_condition',
    category: 'phone',
    orderIndex: 3,
    title: 'What is the physical condition of the phone body?',
    description: 'Inspect back glass/panel, metallic frame edges and camera lens.',
    type: 'single',
    options: [
      {
        id: 'body_flawless',
        label: 'Like Brand New',
        description: 'No dents, scratches or color peeling',
        deductionType: 'percent',
        deductionValue: 0,
        icon: 'shield-check'
      },
      {
        id: 'body_minor_dents',
        label: 'Minor Scratches / 1-2 Dents',
        description: 'Normal everyday pocket wear or minor corner scuffs',
        deductionType: 'flat',
        deductionValue: 900,
        icon: 'layers'
      },
      {
        id: 'body_heavy_damage',
        label: 'Cracked Back / Bent Frame',
        description: 'Rear glass cracked, heavy dents or warped frame',
        deductionType: 'flat',
        deductionValue: 3200,
        icon: 'alert-octagon'
      }
    ]
  },
  {
    id: 'q_functional_issues',
    category: 'phone',
    orderIndex: 4,
    title: 'Are any of these hardware features having issues?',
    description: 'Select any components that are faulty or not operating normally.',
    type: 'multiple',
    options: [
      {
        id: 'func_camera',
        label: 'Camera not focusing / Blur',
        description: 'Front or rear camera has black spots, blur or error',
        deductionType: 'flat',
        deductionValue: 2000,
        icon: 'camera'
      },
      {
        id: 'func_biometrics',
        label: 'Face ID / Fingerprint sensor',
        description: 'Biometric authentication does not register or unlock',
        deductionType: 'flat',
        deductionValue: 1500,
        icon: 'fingerprint'
      },
      {
        id: 'func_speaker_mic',
        label: 'Speaker / Earpiece / Mic',
        description: 'Crackling sound, low volume or other party cannot hear',
        deductionType: 'flat',
        deductionValue: 1000,
        icon: 'volume-x'
      },
      {
        id: 'func_battery',
        label: 'Battery drains fast (<80% health)',
        description: 'Needs charging multiple times a day or swollen',
        deductionType: 'flat',
        deductionValue: 1500,
        icon: 'battery-warning'
      }
    ]
  },
  {
    id: 'q_accessories',
    category: 'phone',
    orderIndex: 5,
    title: 'Do you have original accessories & bill?',
    description: 'Having valid proof of purchase and original box boosts your valuation.',
    type: 'multiple',
    options: [
      {
        id: 'acc_original_charger',
        label: 'Original Brand Charger & Cable',
        description: 'Authentic adapter included with the phone',
        deductionType: 'flat',
        deductionValue: -500, // Negative deduction = bonus!
        icon: 'zap'
      },
      {
        id: 'acc_original_box',
        label: 'Original Device Box (Matching IMEI)',
        description: 'Retail box with intact IMEI sticker',
        deductionType: 'flat',
        deductionValue: -600, // Bonus
        icon: 'package'
      },
      {
        id: 'acc_valid_bill',
        label: 'Original Tax Invoice / Bill',
        description: 'GST invoice matching device serial/IMEI',
        deductionType: 'flat',
        deductionValue: -900, // Bonus
        icon: 'file-text'
      }
    ]
  }
];

export const REFURB_PRODUCTS: RefurbProduct[] = [
  // --- SELBAR EXACT SHOWCASE REFURBISHED PHONES ---
  {
    id: 'rf-samsung-galaxy-m32',
    modelId: 'galaxy-m32',
    brand: 'Samsung',
    name: 'Samsung Galaxy M32 - Refurbished',
    slug: 'renewed-samsung-galaxy-m32',
    category: 'old-phone',
    categoryGroup: 'old-phone',
    conditionType: 'refurbished',
    images: [
      'https://s3n.cashify.in/estore/f25c0b395ebd4793b54ec0404a8232f3.webp',
      'https://s3n.cashify.in/cashify/product/img/xxhdpi/e87178f4-0773.jpg',
      'https://s3n.cashify.in/estore/486d5de9763f47bba50cbb2546380c4e.webp',
      'https://s3n.cashify.in/estore/389893f4857c42a28c43b0644a5c281a.webp',
      'https://s3n.cashify.in/estore/64f4f48918f64f979c9e153771804125.webp',
    ],
    specs: {
      ram: '4 GB / 6 GB',
      storage: '64 GB / 128 GB',
      color: 'Light Blue',
      screen: '6.4" FHD+ Super AMOLED 90Hz',
      processor: 'MediaTek Helio G80 Octa-Core',
      camera: '64MP Quad Rear Camera + 20MP Selfie',
      battery: '6000 mAh Monster Battery',
    },
    grades: [
      {
        grade: 'superb',
        title: 'Superb (Like New)',
        description: 'Screen is completely scratch-free. Flawless body in mint condition.',
        price: 8099,
        originalMrp: 16999,
        stock: 5,
      },
      {
        grade: 'good',
        title: 'Good (Great Value)',
        description: 'Screen has no cracks. Minor micro-scratches on frame. 100% functional.',
        price: 7599,
        originalMrp: 16999,
        stock: 7,
      },
      {
        grade: 'fair',
        title: 'Fair (Best Value)',
        description: 'Noticeable signs of usage on back panel. Fully tested and certified.',
        price: 7299,
        originalMrp: 16999,
        stock: 4,
      },
    ],
    warrantyMonths: 6,
    replacementDays: 15,
    qcPointsCount: 32,
    highlights: [
      '32-Point Rigorous SELBAR Diagnostic Check',
      '6 Months Comprehensive Doorstep Warranty',
      '6000 mAh Monster Battery for 2-Day Endurance',
      '15 Days Hassle-Free Replacement Policy',
    ],
    rating: 4.5,
    reviewCount: 6,
    featured: true,
  },
  {
    id: 'rf-samsung-galaxy-s21-ultra-5g',
    modelId: 'galaxy-s21-ultra',
    brand: 'Samsung',
    name: 'Samsung Galaxy S21 Ultra 5G - Refurbished',
    slug: 'refurbished-samsung-galaxy-s21-ultra-5g',
    category: 'old-phone',
    categoryGroup: 'old-phone',
    conditionType: 'refurbished',
    images: [
      'https://s3ng.cashify.in/cashify/product/img/xxhdpi/5ab3d199-fdb7.jpg',
      'https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-s21-ultra-5g-2.jpg',
      'https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-s21-ultra-5g-4.jpg',
      'https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-s21-ultra-5g-3.jpg',
      'https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-s21-ultra-5g-1.jpg',
    ],
    specs: {
      ram: '12GB',
      storage: '256GB',
      color: 'Phantom Black',
      screen: '6.8" Dynamic AMOLED 2X 120Hz',
      processor: 'Exynos 2100 5G',
      camera: '108MP Quad Camera + 100x Space Zoom',
      battery: '5000 mAh Fast Charging',
    },
    grades: [
      {
        grade: 'superb',
        title: 'Superb (Like New)',
        description: 'Flawless condition with zero scratches. 100% functional.',
        price: 39499,
        originalMrp: 73600,
        stock: 6,
      },
    ],
    warrantyMonths: 12,
    replacementDays: 5,
    qcPointsCount: 32,
    highlights: [
      '32-Point Rigorous Hardware & Battery Certification',
      '12 Months SELBAR Comprehensive Warranty',
      '108MP Flagship Quad Camera with 100X Zoom',
      'Free Doorstep Express Delivery',
    ],
    rating: 4.5,
    reviewCount: 164,
    featured: true,
  },
  {
    id: 'rf-samsung-galaxy-s24-ultra-5g',
    modelId: 'galaxy-s24-ultra',
    brand: 'Samsung',
    name: 'Samsung Galaxy S24 Ultra 5G - Refurbished',
    slug: 'refurbished-samsung-galaxy-s24-ultra-5g',
    category: 'old-phone',
    categoryGroup: 'old-phone',
    conditionType: 'refurbished',
    images: [
      'https://s3ng.cashify.in/cashify/product/img/xxhdpi/a69ef28f-fe68.jpg',
      'https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-s24-ultra-5g-sm-s928-1.jpg',
      'https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-s24-ultra-5g-sm-s928-2.jpg',
      'https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-s24-ultra-5g-sm-s928-3.jpg',
    ],
    specs: {
      ram: '12GB',
      storage: '256GB',
      color: 'Titanium Gray',
      screen: '6.8" Flat Dynamic AMOLED 2X 120Hz',
      processor: 'Snapdragon 8 Gen 3 for Galaxy',
      camera: '200MP + 50MP 5x Telephoto + 10MP 3x + 12MP Ultra',
      battery: '5000 mAh Super Fast 45W',
    },
    grades: [
      {
        grade: 'superb',
        title: 'Superb (Like New)',
        description: 'Titanium frame in mint condition. Built-in S-Pen included.',
        price: 63799,
        originalMrp: 134999,
        stock: 4,
      },
    ],
    warrantyMonths: 12,
    replacementDays: 5,
    qcPointsCount: 32,
    highlights: [
      'Galaxy AI Live Translate & Circle to Search',
      'Armor Aluminum & Titanium Frame Durability',
      '12 Months Full Repair/Replace Warranty',
    ],
    rating: 4.8,
    reviewCount: 92,
    featured: true,
  },
  {
    id: 'rf-samsung-galaxy-s25-edge',
    modelId: 'galaxy-s25-edge',
    brand: 'Samsung',
    name: 'Samsung Galaxy S25 Edge - Refurbished',
    slug: 'refurbished-samsung-galaxy-s25-edge',
    category: 'old-phone',
    categoryGroup: 'old-phone',
    conditionType: 'refurbished',
    images: [
      'https://s3ng.cashify.in/cashify/product/img/xxhdpi/90cb48b8-8691.jpg',
    ],
    specs: {
      ram: '12GB',
      storage: '256GB',
      color: 'Rose Glow',
      screen: '6.7" Dynamic LTPO AMOLED 120Hz',
      processor: 'Snapdragon 8 Elite',
      camera: '50MP OIS + 12MP Telephoto',
      battery: '4800 mAh Fast Wireless Charging',
    },
    grades: [
      {
        grade: 'superb',
        title: 'Superb (Like New)',
        description: 'Pristine aesthetic condition with edge-to-edge curved OLED.',
        price: 52199,
        originalMrp: 125999,
        stock: 5,
      },
    ],
    warrantyMonths: 12,
    replacementDays: 5,
    qcPointsCount: 32,
    highlights: [
      'Stunning Curved Horizon Edge Display',
      'Advanced AI Assistant & Nightography',
      '1 Year SELBAR Warranty with 15-Day Return',
    ],
    rating: 4.8,
    reviewCount: 78,
    featured: true,
  },
  {
    id: 'rf-oneplus-12',
    modelId: 'oneplus-12',
    brand: 'OnePlus',
    name: 'OnePlus 12 - Refurbished',
    slug: 'refurbished-oneplus-12',
    category: 'old-phone',
    categoryGroup: 'old-phone',
    conditionType: 'refurbished',
    images: [
      'https://s3ng.cashify.in/cashify/product/img/xxhdpi/3ba10c91-7df6.jpg',
    ],
    specs: {
      ram: '12GB',
      storage: '256GB',
      color: 'Silky Black',
      screen: '6.82" 2K 120Hz ProXDR Display 4500 nits',
      processor: 'Snapdragon 8 Gen 3',
      camera: '4th Gen Hasselblad 50MP Sony LYT-808',
      battery: '5400 mAh 100W SUPERVOOC',
    },
    grades: [
      {
        grade: 'superb',
        title: 'Superb (Like New)',
        description: 'Flawless condition with 100W rapid charge support.',
        price: 36599,
        originalMrp: 64999,
        stock: 7,
      },
    ],
    warrantyMonths: 12,
    replacementDays: 5,
    qcPointsCount: 32,
    highlights: [
      'Hasselblad Camera for Mobile with Periscope Zoom',
      'Blazing fast 100W wired & 50W wireless charging',
      'Aqua Touch Display Technology',
    ],
    rating: 4.8,
    reviewCount: 112,
    featured: true,
  },
  {
    id: 'rf-samsung-galaxy-z-fold5',
    modelId: 'galaxy-z-fold-5',
    brand: 'Samsung',
    name: 'Samsung Galaxy Z Fold5 - Refurbished',
    slug: 'refurbished-samsung-galaxy-z-fold5',
    category: 'old-phone',
    categoryGroup: 'old-phone',
    conditionType: 'refurbished',
    images: [
      'https://s3ng.cashify.in/cashify/product/img/xxhdpi/57426a66-b6ae.jpg',
    ],
    specs: {
      ram: '12GB',
      storage: '256GB',
      color: 'Icy Blue',
      screen: '7.6" Main QXGA+ & 6.2" Cover Dynamic AMOLED 120Hz',
      processor: 'Snapdragon 8 Gen 2 for Galaxy',
      camera: '50MP Wide + 12MP Ultrawide + 10MP Tele',
      battery: '4400 mAh Dual Battery',
    },
    grades: [
      {
        grade: 'superb',
        title: 'Superb (Like New)',
        description: 'Zero gap Flex Hinge verified. Pristine foldable inner display.',
        price: 69699,
        originalMrp: 84399,
        stock: 3,
      },
    ],
    warrantyMonths: 12,
    replacementDays: 5,
    qcPointsCount: 32,
    highlights: [
      'Flagship Foldable Multitasking Experience',
      'Redesigned Zero-Gap Flex Hinge mechanism',
      '12 Months Extended SELBAR Warranty Protection',
    ],
    rating: 4.9,
    reviewCount: 84,
    featured: true,
  },

  // --- SELBAR EXACT SHOWCASE REFURBISHED LAPTOPS ---
  {
    id: 'rf-apple-macbook-pro-2025-a3434',
    modelId: 'macbook-pro-2025-a3434',
    brand: 'Apple',
    name: 'Apple MacBook Pro 2025 A3434 (Apple M5 14 Inch)- Refurbished',
    slug: 'refurbished-macbook-pro-2025-a3434-apple-m5-14-inch',
    category: 'old-laptop',
    categoryGroup: 'old-laptop',
    conditionType: 'refurbished',
    images: [
      'https://s3ng.cashify.in/cashify/store/product/b63424f7e5494f9bbdfd2c7930930f01.webp',
    ],
    specs: {
      ram: '16GB Unified',
      storage: '512GB SSD',
      color: 'Space Black',
      screen: '14.2" Liquid Retina XDR 120Hz ProMotion',
      processor: 'Apple M5 Pro Chip 12-Core',
      camera: '1080p FaceTime HD with Studio Mics',
      battery: '70 Wh (Health checked >92%)',
    },
    grades: [
      {
        grade: 'superb',
        title: 'Superb (Like New)',
        description: 'Flawless Space Black finish. MagSafe 3 charger included.',
        price: 197599,
        originalMrp: 324999,
        stock: 4,
      },
    ],
    warrantyMonths: 12,
    replacementDays: 5,
    qcPointsCount: 32,
    highlights: [
      'Next-Gen Apple Silicon Architecture',
      'Extreme Dynamic Range with 1600 nits Peak Brightness',
      '12 Months SELBAR Comprehensive Laptop Warranty',
    ],
    rating: 4.8,
    reviewCount: 42,
    featured: true,
  },
  {
    id: 'rf-apple-macbook-pro-2023-a2991',
    modelId: 'macbook-pro-2023-a2991',
    brand: 'Apple',
    name: 'Apple MacBook Pro 2023 A2991 (Apple M3 Pro Chip 16 Inch)- Refurbished',
    slug: 'refurbished-macbook-pro-2023-a2991-apple-m3-pro-chip-16-inch',
    category: 'old-laptop',
    categoryGroup: 'old-laptop',
    conditionType: 'refurbished',
    images: [
      'https://s3ng.cashify.in/cashify/store/product/f133e9311ac34fe2b7737dde73c41206.png',
    ],
    specs: {
      ram: '18GB Unified',
      storage: '512GB SSD',
      color: 'Space Black',
      screen: '16.2" Liquid Retina XDR 120Hz',
      processor: 'Apple M3 Pro Chip (12-core CPU, 18-core GPU)',
      camera: '1080p FaceTime HD',
      battery: '100 Wh (Up to 22 Hours)',
    },
    grades: [
      {
        grade: 'superb',
        title: 'Superb (Like New)',
        description: 'Immaculate condition. 140W USB-C Power Adapter included.',
        price: 152599,
        originalMrp: 198999,
        stock: 1,
      },
    ],
    warrantyMonths: 12,
    replacementDays: 5,
    qcPointsCount: 32,
    highlights: [
      'Hardware-accelerated Ray Tracing & Mesh Shading',
      'Massive 16-Inch Liquid Retina XDR Display',
      '1 Year Warranty & Free Insured Delivery',
    ],
    rating: 4.2,
    reviewCount: 28,
    featured: true,
  },
  {
    id: 'rf-apple-macbook-air-2026-a3449',
    modelId: 'macbook-air-2026-a3449',
    brand: 'Apple',
    name: 'Apple Macbook Air 2026 A3449 (Apple M5 13.3 Inch)- Refurbished',
    slug: 'refurbished-macbook-air-2026-a3449-apple-m5-133-inch',
    category: 'old-laptop',
    categoryGroup: 'old-laptop',
    conditionType: 'refurbished',
    images: [
      'https://s3ng.cashify.in/cashify/store/product/compressed/eb89b2ece08b42b0ad6edef4379be7a7.webp',
    ],
    specs: {
      ram: '16GB Unified',
      storage: '512GB SSD',
      color: 'Midnight Blue',
      screen: '13.6" Liquid Retina 500 nits',
      processor: 'Apple M5 Chip 8-Core',
      camera: '1080p FaceTime HD',
      battery: '52.6 Wh Silent Fanless Design',
    },
    grades: [
      {
        grade: 'superb',
        title: 'Superb (Like New)',
        description: 'Ultra thin and light. Factory-tested battery and logic board.',
        price: 125799,
        originalMrp: 180999,
        stock: 1,
      },
    ],
    warrantyMonths: 12,
    replacementDays: 5,
    qcPointsCount: 32,
    highlights: [
      'Fanless Silent Performance with M5 Efficiency',
      'Midnight Anodization with Anti-fingerprint Seal',
      '12 Months SELBAR Comprehensive Guarantee',
    ],
    rating: 4.0,
    reviewCount: 36,
    featured: true,
  },
  {
    id: 'rf-apple-macbook-air-2025-a3241',
    modelId: 'macbook-air-2025-a3241',
    brand: 'Apple',
    name: 'Apple Macbook Air 2025 A3241 (Apple M4 15 Inch)- Refurbished',
    slug: 'refurbished-macbook-air-2025-a3241-apple-m4-15-inch',
    category: 'old-laptop',
    categoryGroup: 'old-laptop',
    conditionType: 'refurbished',
    images: [
      'https://s3ng.cashify.in/cashify/store/product/a10fa87c0c7b414cb286a84896db2739.png',
    ],
    specs: {
      ram: '16GB Unified',
      storage: '512GB SSD',
      color: 'Starlight',
      screen: '15.3" Liquid Retina 500 nits',
      processor: 'Apple M4 Chip 10-Core',
      camera: '1080p FaceTime HD',
      battery: '66.5 Wh (Up to 18 Hours)',
    },
    grades: [
      {
        grade: 'superb',
        title: 'Superb (Like New)',
        description: 'Immaculate 15-inch aluminum chassis with 35W Dual USB-C Adapter.',
        price: 101599,
        originalMrp: 148999,
        stock: 2,
      },
    ],
    warrantyMonths: 12,
    replacementDays: 5,
    qcPointsCount: 32,
    highlights: [
      'Expansive 15.3-Inch Display in Portable Chassis',
      'Six-speaker sound system with Spatial Audio',
      '1 Year SELBAR Warranty & 15-Day Replacement',
    ],
    rating: 4.8,
    reviewCount: 65,
    featured: true,
  },
  {
    id: 'rf-apple-macbook-pro-2019-touchbar',
    modelId: 'macbook-pro-2019-touchbar',
    brand: 'Apple',
    name: 'Apple MacBook Pro 2019 (Touch Bar, Four Thunderbolt 3)- Refurbished',
    slug: 'refurbished-macbook-pro-2019-touch-bar-four-thunderbolt-3',
    category: 'old-laptop',
    categoryGroup: 'old-laptop',
    conditionType: 'refurbished',
    images: [
      'https://s3ng.cashify.in/cashify/store/product/3315f6f78fb24f9085d4ebc45dd1cc63.png',
    ],
    specs: {
      ram: '16GB LPDDR3',
      storage: '512GB SSD',
      color: 'Silver',
      screen: '13.3" Retina with True Tone and Touch Bar',
      processor: 'Intel Core i5 Quad-Core 2.4 GHz',
      camera: '720p FaceTime HD Camera',
      battery: '58 Wh (Health checked >88%)',
    },
    grades: [
      {
        grade: 'superb',
        title: 'Superb (Like New)',
        description: 'Iconic Touch Bar with Touch ID and 4 High-speed Thunderbolt 3 Ports.',
        price: 60599,
        originalMrp: 96999,
        stock: 5,
      },
    ],
    warrantyMonths: 12,
    replacementDays: 5,
    qcPointsCount: 32,
    highlights: [
      'Interactive Touch Bar with integrated Touch ID',
      'Four Thunderbolt 3 (USB-C) high speed ports',
      '1 Year SELBAR Warranty with Doorstep Service',
    ],
    rating: 4.9,
    reviewCount: 94,
    featured: true,
  },
  {
    id: 'rf-iphone-14-starlight',
    modelId: 'iphone-14',
    brand: 'Apple',
    name: 'Apple iPhone 14 (Refurbished)',
    slug: 'refurbished-apple-iphone-14-128gb',
    category: 'phone',
    images: [
      'https://images.unsplash.com/photo-1663499482523-1c0c1bae4ce1?auto=format&fit=crop&w=800&q=85',
      'https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?auto=format&fit=crop&w=800&q=85',
    ],
    specs: {
      ram: '6GB',
      storage: '128GB',
      color: 'Starlight',
      screen: '6.1" Super Retina XDR OLED',
      processor: 'A15 Bionic chip',
      camera: 'Dual 12MP + 12MP TrueDepth',
      battery: '3279 mAh (100% Health Checked)',
    },
    grades: [
      {
        grade: 'superb',
        title: 'Superb (Like New)',
        description: 'Flawless condition with zero scratches. Looks and feels brand new.',
        price: 46999,
        originalMrp: 69900,
        stock: 5,
      },
      {
        grade: 'good',
        title: 'Good (Minor Signs)',
        description: 'Very light scratches barely visible from 8 inches. 100% functional.',
        price: 43499,
        originalMrp: 69900,
        stock: 8,
      },
      {
        grade: 'fair',
        title: 'Fair (Value Saver)',
        description: 'Visible cosmetic wear on body/edges. Display and camera are 100% fine.',
        price: 39999,
        originalMrp: 69900,
        stock: 3,
      }
    ],
    warrantyMonths: 12,
    replacementDays: 5,
    qcPointsCount: 32,
    highlights: [
      '32-Point Rigorous Hardware & Battery Certification',
      '12 Months Full Repair/Replace SELBAR Warranty',
      '5 Days Hassle-Free Replacement Guarantee',
      'Certified 100% Secure Data-Wiped',
      'Free Fast Doorstep Delivery with Open Box Verification',
    ],
    rating: 4.8,
    reviewCount: 142,
    featured: true,
  },
  {
    id: 'rf-galaxy-s23-phantom-black',
    modelId: 'galaxy-s23',
    brand: 'Samsung',
    name: 'Samsung Galaxy S23 5G (Refurbished)',
    slug: 'refurbished-samsung-galaxy-s23-5g-128gb',
    category: 'phone',
    images: [
      'https://images.unsplash.com/photo-1580910051074-3eb694886505?auto=format&fit=crop&w=800&q=85',
      'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?auto=format&fit=crop&w=800&q=85',
    ],
    specs: {
      ram: '8GB',
      storage: '128GB',
      color: 'Phantom Black',
      screen: '6.1" Dynamic AMOLED 2X 120Hz',
      processor: 'Snapdragon 8 Gen 2 Mobile Platform',
      camera: '50MP + 10MP Tele + 12MP Ultrawide',
      battery: '3900 mAh Fast Charging',
    },
    grades: [
      {
        grade: 'superb',
        title: 'Superb (Like New)',
        description: 'Pristine body and screen. Battery health >90%.',
        price: 42999,
        originalMrp: 74999,
        stock: 4,
      },
      {
        grade: 'good',
        title: 'Good (Minor Signs)',
        description: 'Light cosmetic markings on rim. Flawless AMOLED display.',
        price: 38999,
        originalMrp: 74999,
        stock: 6,
      },
      {
        grade: 'fair',
        title: 'Fair (Value Saver)',
        description: 'Light scuffs on corners. Works seamlessly.',
        price: 34999,
        originalMrp: 74999,
        stock: 2,
      }
    ],
    warrantyMonths: 12,
    replacementDays: 5,
    qcPointsCount: 32,
    highlights: [
      'Snapdragon 8 Gen 2 Flagship Performance',
      'Dynamic AMOLED 2X with Adaptive 120Hz',
      '1 Year SELBAR Warranty & 15-Day Replacement',
      'Box & Compatible 25W Fast Cable Included',
    ],
    rating: 4.7,
    reviewCount: 98,
    featured: true,
  },
  {
    id: 'rf-iphone-13-midnight',
    modelId: 'iphone-13',
    brand: 'Apple',
    name: 'Apple iPhone 13 (Refurbished)',
    slug: 'refurbished-apple-iphone-13-128gb',
    category: 'phone',
    images: [
      'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=800&q=85',
    ],
    specs: {
      ram: '4GB',
      storage: '128GB',
      color: 'Midnight',
      screen: '6.1" Super Retina XDR OLED',
      processor: 'A15 Bionic chip',
      camera: 'Dual 12MP System with Sensor Shift OIS',
      battery: '3227 mAh',
    },
    grades: [
      {
        grade: 'superb',
        title: 'Superb (Like New)',
        description: 'Indistinguishable from brand new. Flawless finish.',
        price: 37999,
        originalMrp: 59900,
        stock: 7,
      },
      {
        grade: 'good',
        title: 'Good (Minor Signs)',
        description: 'Micro scratches on aluminum edge. Mint screen.',
        price: 34499,
        originalMrp: 59900,
        stock: 11,
      },
      {
        grade: 'fair',
        title: 'Fair (Value Saver)',
        description: 'Visible wear on back glass. 100% operational.',
        price: 30999,
        originalMrp: 59900,
        stock: 4,
      }
    ],
    warrantyMonths: 12,
    replacementDays: 5,
    qcPointsCount: 32,
    highlights: [
      'Best Value Refurbished iPhone Deal',
      'Cinema Mode & Night Photography',
      '1 Year Warranty with Free Doorstep Service',
    ],
    rating: 4.9,
    reviewCount: 320,
    featured: true,
  },
  {
    id: 'rf-oneplus-11r-sonic-black',
    modelId: 'oneplus-11r',
    brand: 'OnePlus',
    name: 'OnePlus 11R 5G (Refurbished)',
    slug: 'refurbished-oneplus-11r-5g-128gb',
    category: 'phone',
    images: [
      'https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&w=800&q=85',
    ],
    specs: {
      ram: '8GB',
      storage: '128GB',
      color: 'Sonic Black',
      screen: '6.74" Super Fluid AMOLED 120Hz',
      processor: 'Snapdragon 8+ Gen 1',
      camera: '50MP Sony IMX890 with OIS',
      battery: '5000 mAh 100W SUPERVOOC',
    },
    grades: [
      {
        grade: 'superb',
        title: 'Superb (Like New)',
        description: 'Mint condition with original feel.',
        price: 26999,
        originalMrp: 39999,
        stock: 6,
      },
      {
        grade: 'good',
        title: 'Good (Minor Signs)',
        description: 'Tiny pocket marks on bezel.',
        price: 24499,
        originalMrp: 39999,
        stock: 9,
      }
    ],
    warrantyMonths: 6,
    replacementDays: 5,
    qcPointsCount: 32,
    highlights: [
      'Super Fluid 120Hz Curved AMOLED',
      'Ultra Fast 100W Charging supported',
      '6 Months SELBAR Assured Warranty',
    ],
    rating: 4.6,
    reviewCount: 74,
    featured: false,
    conditionType: 'refurbished',
    categoryGroup: 'old-phone',
  },
  // --- NEW PHONES ---
  {
    id: 'new-iphone-16-pro',
    modelId: 'iphone-16-pro',
    brand: 'Apple',
    name: 'Apple iPhone 16 Pro (Brand New)',
    slug: 'brand-new-apple-iphone-16-pro-128gb',
    category: 'new-phone',
    conditionType: 'new',
    categoryGroup: 'new-phone',
    images: [
      'https://images.unsplash.com/photo-1695048133142-1a20484d2569?auto=format&fit=crop&w=800&q=85',
    ],
    specs: {
      ram: '8GB',
      storage: '128GB',
      color: 'Desert Titanium',
      screen: '6.3" Super Retina XDR with ProMotion 120Hz',
      processor: 'A18 Pro Bionic chip',
      camera: '48MP Fusion + 48MP Ultra Wide + 12MP 5x Telephoto',
      battery: '3582 mAh with Camera Control',
    },
    grades: [
      {
        grade: 'brand-new',
        title: 'Brand New (Factory Sealed)',
        description: 'Original retail box with 100% manufacturer warranty.',
        price: 119900,
        originalMrp: 119900,
        stock: 12,
      },
    ],
    warrantyMonths: 12,
    replacementDays: 5,
    qcPointsCount: 32,
    highlights: [
      '1 Year Official Apple India Manufacturer Warranty',
      'Factory Sealed Brand New Box Pack',
      'Camera Control Button & Apple Intelligence Ready',
      'Free Express Insured Delivery',
    ],
    rating: 5.0,
    reviewCount: 48,
    featured: true,
  },
  {
    id: 'new-s25-ultra',
    modelId: 'galaxy-s25-ultra',
    brand: 'Samsung',
    name: 'Samsung Galaxy S25 Ultra 5G (Brand New)',
    slug: 'brand-new-samsung-galaxy-s25-ultra-256gb',
    category: 'new-phone',
    conditionType: 'new',
    categoryGroup: 'new-phone',
    images: [
      'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?auto=format&fit=crop&w=800&q=85',
    ],
    specs: {
      ram: '12GB',
      storage: '256GB',
      color: 'Titanium Silverblue',
      screen: '6.8" Dynamic AMOLED 2X 120Hz Anti-Reflective',
      processor: 'Snapdragon 8 Elite for Galaxy',
      camera: '200MP Quad Telephoto System',
      battery: '5000 mAh 45W Fast Charging',
    },
    grades: [
      {
        grade: 'brand-new',
        title: 'Brand New (Factory Sealed)',
        description: 'Original box pack with Samsung 1-Year National Warranty.',
        price: 129999,
        originalMrp: 134999,
        stock: 9,
      },
    ],
    warrantyMonths: 12,
    replacementDays: 5,
    qcPointsCount: 32,
    highlights: [
      '1 Year Official Samsung India Warranty',
      'Galaxy AI Features & Built-in S-Pen',
      'Corning Gorilla Armor Glass Protection',
    ],
    rating: 4.9,
    reviewCount: 32,
    featured: true,
  },
  // --- NEW LAPTOPS ---
  {
    id: 'new-macbook-air-m3',
    modelId: 'macbook-air-m3',
    brand: 'Apple',
    name: 'Apple MacBook Air 13.6" M3 (Brand New)',
    slug: 'brand-new-apple-macbook-air-m3-8gb-256gb',
    category: 'new-laptop',
    conditionType: 'new',
    categoryGroup: 'new-laptop',
    images: [
      'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=800&q=85',
    ],
    specs: {
      ram: '8GB Unified',
      storage: '256GB SSD',
      color: 'Midnight',
      screen: '13.6" Liquid Retina Display 500 nits',
      processor: 'Apple M3 Chip (8-Core CPU, 8-Core GPU)',
      camera: '1080p FaceTime HD Camera',
      battery: 'Up to 18 Hours Battery Life',
    },
    grades: [
      {
        grade: 'brand-new',
        title: 'Brand New (Sealed)',
        description: 'Original Apple Retail Box with MagSafe 3 cable.',
        price: 104900,
        originalMrp: 114900,
        stock: 7,
      },
    ],
    warrantyMonths: 12,
    replacementDays: 5,
    qcPointsCount: 32,
    highlights: [
      '1 Year Official Apple India Warranty',
      'Blazing-fast M3 Performance with AV1 Decode',
      'Support for up to Two External Displays',
    ],
    rating: 4.9,
    reviewCount: 61,
    featured: true,
  },
  {
    id: 'new-hp-pavilion-15',
    modelId: 'hp-pavilion-15',
    brand: 'HP',
    name: 'HP Pavilion 15 Core i5 13th Gen (Brand New)',
    slug: 'brand-new-hp-pavilion-15-16gb-512gb',
    category: 'new-laptop',
    conditionType: 'new',
    categoryGroup: 'new-laptop',
    images: [
      'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?auto=format&fit=crop&w=800&q=85',
    ],
    specs: {
      ram: '16GB DDR4',
      storage: '512GB NVMe SSD',
      color: 'Natural Silver',
      screen: '15.6" Full HD IPS Micro-edge Anti-glare',
      processor: 'Intel Core i5-1335U (Up to 4.6 GHz)',
      camera: 'HP Wide Vision 720p HD',
      battery: '3-cell 41 Wh Li-ion Fast Charge',
    },
    grades: [
      {
        grade: 'brand-new',
        title: 'Brand New (Factory Pack)',
        description: 'Brand new with HP Onsite 1-Year Warranty.',
        price: 56990,
        originalMrp: 68900,
        stock: 14,
      },
    ],
    warrantyMonths: 12,
    replacementDays: 5,
    qcPointsCount: 32,
    highlights: [
      '1 Year Official HP India Onsite Warranty',
      'Backlit Keyboard & Fingerprint Reader',
      'Pre-installed Windows 11 & MS Office',
    ],
    rating: 4.8,
    reviewCount: 29,
    featured: false,
  },
  // --- OLD / REFURBISHED LAPTOPS ---
  {
    id: 'old-macbook-pro-m1',
    modelId: 'macbook-pro-m1',
    brand: 'Apple',
    name: 'Apple MacBook Pro 13" M1 (Refurbished)',
    slug: 'refurbished-apple-macbook-pro-13-m1-8gb-256gb',
    category: 'old-laptop',
    conditionType: 'refurbished',
    categoryGroup: 'old-laptop',
    images: [
      'https://images.unsplash.com/photo-1541807084-5c52b6b3adef?auto=format&fit=crop&w=800&q=85',
    ],
    specs: {
      ram: '8GB Unified',
      storage: '256GB SSD',
      color: 'Space Gray',
      screen: '13.3" Retina Display with Touch Bar',
      processor: 'Apple M1 Chip 8-Core',
      camera: '720p FaceTime HD',
      battery: '58.2 Wh (Health >88%)',
    },
    grades: [
      {
        grade: 'superb',
        title: 'Superb (Like New)',
        description: 'Zero body dents. Keyboard and Retina screen in flawless state.',
        price: 54999,
        originalMrp: 122900,
        stock: 5,
      },
      {
        grade: 'good',
        title: 'Good (Minor Scuffs)',
        description: 'Light wear on corner chamfer. 100% certified hardware.',
        price: 49999,
        originalMrp: 122900,
        stock: 8,
      },
    ],
    warrantyMonths: 12,
    replacementDays: 5,
    qcPointsCount: 32,
    highlights: [
      '12 Months SELBAR Comprehensive Warranty',
      'Active Cooling for Sustained Pro Workflows',
      'Tested 32-Point Battery & Hardware Check',
    ],
    rating: 4.9,
    reviewCount: 88,
    featured: true,
  },
  {
    id: 'old-thinkpad-t14',
    modelId: 'thinkpad-t14',
    brand: 'Lenovo',
    name: 'Lenovo ThinkPad T14 Gen 2 (Refurbished)',
    slug: 'refurbished-lenovo-thinkpad-t14-gen-2-i5',
    category: 'old-laptop',
    conditionType: 'refurbished',
    categoryGroup: 'old-laptop',
    images: [
      'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=800&q=85',
    ],
    specs: {
      ram: '16GB RAM',
      storage: '512GB SSD',
      color: 'Matte Black',
      screen: '14" FHD IPS Anti-glare 300 nits',
      processor: 'Intel Core i5-1145G7 vPro',
      camera: '720p HD with ThinkShutter Privacy',
      battery: '50 Wh Battery with Rapid Charge',
    },
    grades: [
      {
        grade: 'superb',
        title: 'Superb (A+ Grade)',
        description: 'Legendary ThinkPad military-grade build with mint keyboard.',
        price: 28999,
        originalMrp: 84999,
        stock: 10,
      },
    ],
    warrantyMonths: 12,
    replacementDays: 5,
    qcPointsCount: 32,
    highlights: [
      'Legendary Spill-resistant ThinkPad Keyboard',
      'Enterprise Durability & vPro Security',
      '1 Year SELBAR Warranty & Free Delivery',
    ],
    rating: 4.8,
    reviewCount: 45,
    featured: true,
  },
  // --- NEW DESKTOPS ---
  {
    id: 'new-imac-24-m3',
    modelId: 'imac-24-m3',
    brand: 'Apple',
    name: 'Apple iMac 24" 4.5K Retina M3 (Brand New)',
    slug: 'brand-new-apple-imac-24-m3-8gb-256gb',
    category: 'new-desktop',
    conditionType: 'new',
    categoryGroup: 'new-desktop',
    images: [
      'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=800&q=85',
    ],
    specs: {
      ram: '8GB Unified',
      storage: '256GB SSD',
      color: 'Blue',
      screen: '24" 4.5K Retina Display (4480x2520)',
      processor: 'Apple M3 Chip (8-Core CPU, 8-Core GPU)',
      camera: '1080p FaceTime HD with Studio-quality mics',
      battery: 'AC Power (Includes Magic Keyboard & Magic Mouse)',
    },
    grades: [
      {
        grade: 'brand-new',
        title: 'Brand New (Sealed Pack)',
        description: 'Original Apple India retail packaging with color-matched accessories.',
        price: 134900,
        originalMrp: 134900,
        stock: 5,
      },
    ],
    warrantyMonths: 12,
    replacementDays: 5,
    qcPointsCount: 32,
    highlights: [
      '1 Year Official Apple India Warranty',
      'Stunning 11.5mm Ultra-thin All-in-One Design',
      'Six-Speaker Sound System with Spatial Audio',
    ],
    rating: 5.0,
    reviewCount: 19,
    featured: true,
  },
  {
    id: 'new-asus-rog-strix-desktop',
    modelId: 'asus-rog-strix-pc',
    brand: 'ASUS',
    name: 'ASUS ROG Strix Gaming PC Tower (Brand New)',
    slug: 'brand-new-asus-rog-strix-gaming-pc-rtx4060',
    category: 'new-desktop',
    conditionType: 'new',
    categoryGroup: 'new-desktop',
    images: [
      'https://images.unsplash.com/photo-1587202372775-e229f172b9d7?auto=format&fit=crop&w=800&q=85',
    ],
    specs: {
      ram: '16GB DDR5 5600MHz',
      storage: '1TB M.2 NVMe PCIe 4.0 SSD',
      color: 'Star Black with Aura Sync RGB',
      screen: 'Supports Multiple 4K/8K Gaming Displays',
      processor: 'Intel Core i5-14400F 14th Gen',
      camera: 'Not Included (Gaming Rig)',
      battery: '500W 80 PLUS Bronze Power Supply',
    },
    grades: [
      {
        grade: 'brand-new',
        title: 'Brand New (Factory Sealed)',
        description: 'Pre-built high performance gaming tower with NVIDIA RTX 4060 8GB.',
        price: 89999,
        originalMrp: 109999,
        stock: 6,
      },
    ],
    warrantyMonths: 36,
    replacementDays: 5,
    qcPointsCount: 32,
    highlights: [
      '3 Years Comprehensive ASUS Onsite Warranty',
      'NVIDIA GeForce RTX 4060 Dedicated Graphics',
      'Optimized Airflow Chassis & Aura Sync RGB',
    ],
    rating: 4.9,
    reviewCount: 38,
    featured: true,
  },
  // --- OLD / REFURBISHED DESKTOPS ---
  {
    id: 'old-imac-27-5k',
    modelId: 'imac-27-5k',
    brand: 'Apple',
    name: 'Apple iMac 27" 5K Retina Core i7 (Refurbished)',
    slug: 'refurbished-apple-imac-27-5k-retina-32gb-1tb',
    category: 'old-desktop',
    conditionType: 'refurbished',
    categoryGroup: 'old-desktop',
    images: [
      'https://images.unsplash.com/photo-1517059224940-d4af9eec41b7?auto=format&fit=crop&w=800&q=85',
    ],
    specs: {
      ram: '32GB DDR4',
      storage: '1TB Fusion/SSD',
      color: 'Silver Aluminum',
      screen: '27" 5K Retina Display (5120x2880)',
      processor: 'Intel Core i7 3.8GHz Quad-Core',
      camera: 'FaceTime HD Camera with Stereo Speakers',
      battery: 'AC Power (Includes Power Cable)',
    },
    grades: [
      {
        grade: 'superb',
        title: 'Superb (Like New)',
        description: 'Massive 5K color-accurate screen. Ideal for photo & video editing.',
        price: 46999,
        originalMrp: 169900,
        stock: 4,
      },
    ],
    warrantyMonths: 12,
    replacementDays: 5,
    qcPointsCount: 32,
    highlights: [
      'Breathtaking 27-inch 5K Retina Screen',
      'Upgraded 32GB RAM for Heavy Multitasking',
      '1 Year Full SELBAR Warranty with Doorstep Service',
    ],
    rating: 4.8,
    reviewCount: 52,
    featured: true,
  },
  {
    id: 'old-dell-optiplex-7070',
    modelId: 'dell-optiplex-7070',
    brand: 'Dell',
    name: 'Dell OptiPlex 7070 Micro PC (Refurbished)',
    slug: 'refurbished-dell-optiplex-7070-micro-i5-16gb',
    category: 'old-desktop',
    conditionType: 'refurbished',
    categoryGroup: 'old-desktop',
    images: [
      'https://images.unsplash.com/photo-1593640408182-31c70c8268f5?auto=format&fit=crop&w=800&q=85',
    ],
    specs: {
      ram: '16GB DDR4',
      storage: '512GB NVMe SSD',
      color: 'Business Black',
      screen: 'Compact Micro Form Factor (Supports 3 Displays)',
      processor: 'Intel Core i5-9500T (Up to 3.7 GHz)',
      camera: 'Not Included (Micro Desktop)',
      battery: 'External Power Adapter',
    },
    grades: [
      {
        grade: 'superb',
        title: 'Superb (Commercial Refurb)',
        description: 'Ultra compact palm-sized business PC with genuine Windows 11 Pro.',
        price: 18499,
        originalMrp: 62000,
        stock: 12,
      },
    ],
    warrantyMonths: 12,
    replacementDays: 5,
    qcPointsCount: 32,
    highlights: [
      'Compact Palm-Sized Ultra Small Form Factor',
      'High Reliability Dell Commercial OptiPlex Series',
      '1 Year SELBAR Warranty & Genuine Windows 11 Pro',
    ],
    rating: 4.7,
    reviewCount: 41,
    featured: false,
  }
];

// In-Memory dynamic store for simulated orders & quotes
export interface DatabaseState {
  quotes: Map<string, Quote>;
  sellOrders: Map<string, SellOrder>;
  buyOrders: Map<string, BuyOrder>;
}

declare global {
  // eslint-disable-next-line no-var
  var __selbar_db: DatabaseState | undefined;
}

const initialSellOrders: SellOrder[] = [];
const initialBuyOrders: BuyOrder[] = [];

const initialDb: DatabaseState = {
  quotes: new Map(),
  sellOrders: new Map(),
  buyOrders: new Map(),
};

export const db: DatabaseState = global.__selbar_db ?? initialDb;
if (process.env.NODE_ENV !== 'production') {
  global.__selbar_db = db;
}
